TERMUX_PKG_HOMEPAGE=https://mitmproxy.org
TERMUX_PKG_DESCRIPTION="Interactive HTTPS proxy"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@Sb-Bot-s"

TERMUX_PKG_VERSION="12.2.3"
TERMUX_PKG_SRCURL=https://downloads.mitmproxy.org/${TERMUX_PKG_VERSION}/mitmproxy-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=2a4fca401f433d786f768036718d2bde6d8490a4963a5e5aa70e1e07c0f1695d

TERMUX_PKG_DEPENDS="python"
TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS="setuptools,wheel"

TUR_AUTO_BUILD_WHEEL=true

source $TERMUX_SCRIPTDIR/common-files/tur_build_wheel.sh
